package com.view;

public enum MainSpriteEnum {
    CORE_SLAB,
    SLAB, SLAB_BIS,
    PIPE_H, PIPE_V,
    PIPE_LT, PIPE_BR,
    PIPE_TR, PIPE_LB,
    GRASS, GRASS_BB,
    GRASS_TB, GRASS_LB,
    GRASS_RB, GRASS_BRB,
    GRASS_BLB, GRASS_TLB,
    GRASS_TRB, TOPWALL_ONE,
    TOPWALL_TWO, TOPWALL_THREE,
    BRICK_BR, BRICK_LB,
    BRICK_LT, BRICK_RT,
    TREE_ONE, TREE_TWO,
    WALL_ONE, WALL_TWO, WALL_THREE,
    RIGHT_WALL, LEFT_WALL,
    STRAIGHT_ARROW, SOURCE_ARROW,
    TURN_ARROW, END_ARROW,
    MOVE,ATTACK,
    KN_I0, KN_I1, KN_I2, KN_I3,KN_I4,KN_I5,KN_I6,
    F_I0, F_I1, F_I2, F_I3, F_I4,F_I5, F_I6
}
